# Generated by Django 4.2.2 on 2023-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_catagory_image_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest',
            field=models.BooleanField(default=False, help_text='0-default,1-Latest'),
        ),
    ]
