# Generated by Django 4.2.2 on 2023-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
