# Generated by Django 4.2.2 on 2023-06-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_product_trending_product_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Trending',
            new_name='trending',
        ),
    ]
