# Generated by Django 4.2.2 on 2023-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_rename_trending_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
    ]
