# Generated by Django 4.2.2 on 2023-07-04 12:46

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_alter_cart_id_alter_catagory_id_alter_catagory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=ecom.models.getFileName),
        ),
    ]
