# Generated by Django 4.2.2 on 2023-09-02 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0020_product_watchhour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ytsell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Whatsapp', models.IntegerField(max_length=20)),
                ('Channel_Link', models.CharField(max_length=1000)),
                ('Subscribers', models.IntegerField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Price', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
