# Generated by Django 4.2.2 on 2023-09-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_ytsell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytsell',
            old_name='name',
            new_name='Name',
        ),
    ]
