# Generated by Django 4.2.2 on 2023-09-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_rename_name_ytsell_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytsell',
            old_name='Name',
            new_name='ytsellName',
        ),
    ]
