# Generated by Django 4.2.2 on 2023-09-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_rename_name_ytsell_ytsellname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytsell',
            old_name='ytsellName',
            new_name='ytsellname',
        ),
    ]
