# Generated by Django 4.2.2 on 2023-09-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_rename_ytsellname_ytsell_ytsellname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytsell',
            name='user',
        ),
    ]
