# Generated by Django 4.2.2 on 2023-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_remove_ytsell_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ytservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytsellname', models.CharField(max_length=100)),
                ('Whatsapp', models.IntegerField(max_length=20)),
                ('Channel_Link', models.CharField(max_length=1000)),
                ('Subscribers', models.IntegerField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Price', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
