# Generated by Django 4.2.2 on 2023-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_ytservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytservice',
            old_name='Price',
            new_name='Views',
        ),
        migrations.RemoveField(
            model_name='ytservice',
            name='Status',
        ),
        migrations.AddField(
            model_name='ytservice',
            name='Watch_hour',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
