# Generated by Django 4.2.2 on 2023-09-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_rename_price_ytservice_views_remove_ytservice_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ytservice',
        ),
    ]
