# Generated by Django 4.2.2 on 2023-09-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0028_delete_ytservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ytservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytname', models.CharField(max_length=100)),
                ('Whatsapp_number', models.IntegerField(max_length=20)),
                ('ytChannel_Link', models.CharField(max_length=1000)),
                ('ytSubscribers', models.IntegerField(max_length=100)),
                ('ytStatus', models.CharField(max_length=100)),
                ('ytPrice', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
