# Generated by Django 4.2.2 on 2023-09-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_ytservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Detail',
            new_name='Subscriber',
        ),
    ]
